# Generated by Django 4.0.6 on 2022-07-22 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 13, 13, 6, 950465), verbose_name='date published'),
        ),
        migrations.AlterModelTable(
            name='tutorialcategory',
            table='Categories',
        ),
    ]
