# Generated by Django 4.0.6 on 2022-07-22 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tutorialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 13, 24, 48, 661550), verbose_name='date published'),
        ),
        migrations.AlterModelTable(
            name='tutorialcategory',
            table=None,
        ),
    ]
