# Generated by Django 4.0.6 on 2022-07-28 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tutorialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 1, 45, 434866), verbose_name='date published'),
        ),
    ]
