# Generated by Django 4.0.6 on 2022-07-28 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 22, 30, 850933), verbose_name='date published'),
        ),
    ]
