# Generated by Django 4.0.6 on 2022-07-28 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 25, 14, 578707), verbose_name='date published'),
        ),
    ]
